# Display a box
print("\t ##########")
print("\t #  *  *  #")
print("\t #    _   #")
print("\t ##########")
print("\t \t ##")
print("\t #########")
print("\t # ##### #")
print("\t # ##### #")
print("\t # ##### #")
print("\t # ##### #")
print("\t   ## ##  ")
print("\t   ## ##  ")
print("\t   ## ##  ")
print("\t   ## ##  ")
print("\t   ## ##  ")
